project:
  type: website

website:
  title: "MIMIS Workshop 2024"
  navbar:
    left:
      - href: index.qmd
      - href: S1.qmd
        text: Sesión 1
      - href: S2.qmd
        text: Sesión 2
      - href: S3.qmd
        text: Sesión 3
lang: es    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



