on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libmagick++-dev texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      - name: Install tinytex package
        run: R -e "install.packages('tinytex')"

      - name: Install TinyTeX
        run: R -e "tinytex::install_tinytex(force = TRUE)"

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Reinstall magick if needed
        run: R -e "install.packages('magick', repos='http://cran.r-project.org')"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display LaTeX log if compilation fails
        if: failure()
        run: cat tex_tempDoc.log || true
